name: ci

on:
  push:
    branches:
      - main

env:
  REPO: atareao/retwitter

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Install the latest version of rye
        id: install_rye
        uses: eifinger/setup-rye@v4
      - name: Get current version
        id: get_current_version
        run: |
          current_version=$(rye version)
          echo "current_version=${current_version}" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: "${{ env.REPO }}:v${{ steps.get_current_version.outputs.current_version }},${{ env.REPO }}:latest"
